apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  namespace: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2  # Run 2 copies of the app
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: sample-python-app
        image: dheerpala1/sample-python-app:${BUILD_NUMBER}  # Your Docker image
        imagePullPolicy: Always  # Always pull latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5